# ضع هذا في: /etc/nginx/sites-available/zonex
# غيّر DOMAIN.COM لدومينك الحقيقي.
# لازم السوكِت هنا يطابق اللي في gunicorn.service:  /run/gunicorn.sock

server {
    listen 80;
    server_name DOMAIN.COM www.DOMAIN.COM;

    client_max_body_size 10M;   # للسماح برفع صور الإيصالات

    location /static/ {
        alias /var/www/ZoneX-Portal/staticfiles/;
    }

    location /media/ {
        alias /var/www/ZoneX-Portal/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
