# Generated by Django 6.0.6 on 2026-06-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=120, verbose_name='اسم المحل')),
                ('owner_name', models.CharField(max_length=120, verbose_name='اسم صاحب المحل')),
                ('phone', models.CharField(max_length=40, verbose_name='رقم الهاتف / واتساب')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد (اختياري)')),
                ('country', models.CharField(choices=[('SY', 'سوريا'), ('TR', 'تركيا'), ('OTHER', 'دولة أخرى')], default='SY', max_length=10, verbose_name='الدولة')),
                ('plan', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', '٣ أشهر'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='الباقة')),
                ('price', models.FloatField(default=0, verbose_name='السعر ($)')),
                ('payment_method', models.CharField(blank=True, choices=[('shamcash', 'شام كاش (سوريا)'), ('kuwaitturk', 'Kuwait Türk (تركيا)'), ('other', 'طريقة أخرى')], max_length=20, null=True, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True, verbose_name='رقم العملية')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='صورة الإيصال')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الدفع'), ('submitted', 'بانتظار المراجعة'), ('approved', 'مُفعّل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('license_key', models.CharField(blank=True, max_length=60, null=True, verbose_name='كود التفعيل')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظة الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التفعيل')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
