# Generated by Django 6.0.6 on 2026-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='manager_password',
            field=models.CharField(default='1234', max_length=50, verbose_name='كلمة سر المدير'),
        ),
    ]
