# Generated by Django 6.0.6 on 2026-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_manager_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='machine_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='معرّف الجهاز المربوط'),
        ),
    ]
